AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.5

Bundler/OrderedGems:
  Exclude:
    - 'Gemfile'
    - 'gemfiles/*'

Gemspec/OrderedDependencies:
  Exclude:
    - 'carrierwave.gemspec'

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/DotPosition:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Layout/SpaceBeforeBlockBraces:
  Enabled: false

Layout/SpaceInsideBlockBraces:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Layout/SpaceInsideParens:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/AmbiguousRegexpLiteral:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'spec/processing/rmagick_spec.rb'

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UselessMethodDefinition:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Max: 5

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 28

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 31

Naming/AccessorMethodName:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'gemfiles/*'

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateName:
  Exclude:
    - 'spec/**/*'
    - 'lib/carrierwave/sanitized_file.rb'
    - 'lib/carrierwave/test/matchers.rb'

Naming/VariableNumber:
  Enabled: false

Security/Eval:
  Exclude:
    - 'lib/carrierwave/uploader/configuration.rb'
    - 'spec/storage/fog_helper.rb'

Security/Open:
  Exclude:
    - 'spec/storage/fog_helper.rb'

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BlockDelimiters:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/tmp/app/uploaders/my_module/avatar_uploader.rb'

Style/ClassVars:
  Exclude:
    - 'lib/carrierwave/uploader/cache.rb'

Style/CommentedKeyword:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/EvalWithLocation:
  Exclude:
    - 'spec/storage/fog_helper.rb'

Style/FormatString:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: template

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 11

Style/OptionalBooleanParameter:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RedundantRegexpCharacterClass:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SlicingWithRange:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringConcatenation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  MinSize: 8

Style/ZeroLengthPredicate:
  Enabled: false

Layout/LineLength:
  Max: 256
